[package]
name = "actix_ins"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "*"
serde = { version = "*", features = ["derive"] }
futures = "*"
env_logger = "*"
log = "*"
derive_more = "*"

[[example]]
name = "user_api"
path = "examples/user_api.rs"